version: "3.8"

services:
  traefik:
    image: traefik:2.9.8
    container_name: traefik
    restart: always
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik

    # traefik
    command:
      # provider
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      # log
      - --log.level=INFO

      # access log
      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik/access.json
      - --accesslog.format=json

      # dashboard
      - --api=true
      - --api.dashboard=true

      # entry points
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https

      # for https
      - --entrypoints.websecure.address=:443

      # certificate
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.keyType=EC384

      # # LetsEncrypt Staging Server - uncomment when testing
      # - --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      # # - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      # # - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http

      # # When using CloudFlare as proxy DNS challenge is required
      # - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      # - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      # - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=0
      # - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      # - --certificatesresolvers.letsencrypt.acme.email=${EMAIL}
      # - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.to-https.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.to-https.entrypoints=web
      - traefik.http.routers.to-https.middlewares=to-https
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=${TRAEFIK_CERT_RESOLVER}
      - traefik.http.middlewares.to-https.redirectscheme.scheme=https
      - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD_HASH}
    volumes:
      - ./data/letsencrypt:/letsencrypt
      - ./data/logs:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  traefik:
    name: traefik