# syntax=docker.io/docker/dockerfile:1

FROM node:20-alpine AS base


ARG MEDUSA_BACKEND_URL
ARG NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
ENV MEDUSA_BACKEND_URL=${MEDUSA_BACKEND_URL}
ENV NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY}

# Set the working directory
WORKDIR /app

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat git

# Clone the repository
RUN git clone https://github.com/medusajs/nextjs-starter-medusa.git /app

# Install dependencies based on the preferred package manager
RUN corepack enable yarn && yarn install

# Set environment variable to disable telemetry
ENV NEXT_TELEMETRY_DISABLED=1

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app ./

RUN apk add --no-cache curl jq

ARG EMAIL
ARG PASSWORD
ENV EMAIL=${EMAIL}
ENV PASSWORD=${PASSWORD}

COPY ./.env ./.env
COPY ./storefront.next.config.js ./next.config.js

# Obtain the publishable key if NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY is not set
COPY ./create-publishable-key.sh /app/create-publishable-key.sh
RUN chmod +x /app/create-publishable-key.sh

RUN corepack enable yarn && NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=$(sh /app/create-publishable-key.sh -u $MEDUSA_BACKEND_URL -e $EMAIL -p $PASSWORD) yarn run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

COPY ./replace-env-vars.sh /app/replace-env-vars.sh
RUN chmod +x /app/replace-env-vars.sh

USER nextjs

EXPOSE 8000

ENV PORT=8000

ENV NODE_ENV=production

ENV HOSTNAME="0.0.0.0" 

ENTRYPOINT ["sh", "-c", "/app/replace-env-vars.sh && node server.js"]