# Use Node.js 20 as a parent image
FROM node:20 AS builder

# Set the working directory
WORKDIR /app

# Clone the repository
RUN git clone {{baseRepository}} .

# Copy the local medusa-config.ts file to override the existing one
COPY medusa/medusa-config.ts /app/medusa-config.ts

# Copy Medusa helper scripts
COPY medusa/seed.ts /app/medusa/seed.ts
COPY medusa/check-seed.ts /app/src/scripts/check-seed.ts
COPY medusa/check-user-exists.ts /app/src/scripts/check-user-exists.ts

COPY entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

# Install dependencies
RUN yarn install

# Build the application
RUN yarn build

# SECOND STAGE: Minimal image for running the application
FROM node:20-slim

# Set the working directory
WORKDIR /app

# Copy necessary files from the builder stage
COPY --from=builder /app .

# Expose the application port
EXPOSE 9000

ENTRYPOINT [ "/app/entrypoint.sh" ]