version: "3.8"

services:
  storage:
    image: minio/minio:latest
    container_name: service-storage
    restart: unless-stopped
    command: server /data --console-address :9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./data/storage:/data
    networks:
      - traefik
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASS}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      # api
      - traefik.http.services.storage.loadbalancer.server.port=9000
      - traefik.http.routers.storage.entrypoints=websecure
      - traefik.http.routers.storage.service=storage
      - traefik.http.routers.storage.rule=Host(`${MINIO_DOMAIN}`)
      - traefik.http.routers.storage.tls.certresolver=${MINIO_CERT_RESOLVER}
      # console
      - traefik.http.services.minio-console.loadbalancer.server.port=9001
      - traefik.http.routers.minio-console.entrypoints=websecure
      - traefik.http.routers.minio-console.service=minio-console
      - traefik.http.routers.minio-console.rule=Host(`${MINIO_CONSOLE_DOMAIN}`)      
      - traefik.http.routers.minio-console.tls.certresolver=${MINIO_CERT_RESOLVER}

networks:
  traefik:
    name: traefik